apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/andersonmoura87/microservices-fastapi-platform.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-prod
  syncPolicy:
    # Prod syncs are manual on purpose: a human promotes the release.
    syncOptions:
      - CreateNamespace=true
