version: 2
updates:
  - package-ecosystem: pip
    directory: /services/api-gateway
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /services/user-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /services/data-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /services/api-gateway
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /services/user-service
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /services/data-service
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
